### ISSUE TITLE
Make Catalog/Services configurable via PCF tile

### ISSUE THREAD

**Issue by spiegela** [codedellemc/ecs-broker-boshrelease#3]
Currently the tile includes base configuration, but doesn't allow for customization of services and plans for namespaces and buckets. This will limit tile-based to deploys to situations when the default services are acceptable, which will be relatively few production deployments.

**Comment by msalem2** [comment]
I started this enhancement with bosh release itself, I am still in testing. I will take it to the tile after the initial publishing as public beta.

**Comment by spiegela** [comment]
Closed by https://github.com/codedellemc/ecs-broker-tile/pull/1
