### ISSUE TITLE
Provide additional notes for Object-Endpoint and Base URL

### ISSUE THREAD

**Issue by spiegela** [codedellemc/ecs-broker-boshrelease#4]
The current tile UI should probably provide a bit more explanation on how the `object-endpoint`, `base-url` and `repository-endpoint` parameters interact.

The preferred method for broker configuration, should probably be the `base-url`.  This allows the user to specify the _name_ of the ECS configured "Base URL", and lookup the actual hostname through the ECS management API.

The `object-endpoint` is a way to configure the URL directly, without the use of a "Base URL" for situations when the actual URL is not configured in ECS.  I think this should be relatively rare, but we ran into it when supporting [ECS TestDrive](https://portal.ecstestdrive.com/).

The `repository-endpoint` is a way to override the object endpoint, when the repository bucket is accessible via a different endpoint than the buckets.  Again, somewhat rare.

**Comment by msalem2** [comment]
This will make more sense to add more detail so we can explain the difference between the parameters.

**Comment by spiegela** [comment]
Closed by https://github.com/codedellemc/ecs-broker-tile/pull/1
