### ISSUE TITLE
Add new catalog icon

### ISSUE THREAD

**Issue by spiegela** [codedellemc/ecs-broker-boshrelease#5]
The one that I used originally scales kind of strange in the PCF apps-manager UI.  Maybe we should use this one from the EMCECS GH org?

![image](https://cloud.githubusercontent.com/assets/3212/26280403/de4f0258-3d97-11e7-9701-b181030d1b40.png)

It looks pretty nice.  Should probably find a way to incorporate it in the BOSH release instead of serving it over the internet, too. Maybe put it in the repository bucket...

**Comment by msalem2** [comment]
I tried to use this icon with the tile and it did not look good when it was resized. I am using the attached icon
![icon](https://user-images.githubusercontent.com/9592178/27588069-afe52934-5afb-11e7-9596-ff637262735c.png)
